"""Orchestration for the existing Divide & Combine feature workflow.

The split, mapping and combine operations remain in
``scripts.feature_block_dataset_tools``.  This module only connects those
operations with the regular :mod:`src.workflow` experiment runner.
"""

from __future__ import annotations

import time
from dataclasses import replace
from pathlib import Path

from scripts.feature_block_dataset_tools import (
    CombineOptions,
    PROJECT_ROOT,
    SplitOptions,
    combine_selected_features,
    dataset_base_name,
    split_dataset_by_features,
)
from src.config import ExperimentConfig
from src.output_paths import task_output_dir
from src.reporting import collect_run_row, save_repeated_run_tables


DEFAULT_BLOCK_COUNT = 10


def _percent_tag(feature_percent: float) -> str:
    value = float(feature_percent)
    return str(int(value)) if value.is_integer() else str(value).replace(".", "_")


def _selection_output_root(task: str) -> Path:
    # Clustering intentionally shares the FeatureRank list generated by the
    # classification helpers (the established clustering implementation does
    # the same through ensure_shared_selected_features()).
    output_task = "classification" if task == "clustering" else task
    return task_output_dir(output_task, ".")


def run_divide_combine(
    config: ExperimentConfig,
    block_count: int = DEFAULT_BLOCK_COUNT,
) -> tuple[float, float]:
    """Run split -> block FeatureRank -> mapped combine -> final evaluation."""
    if block_count < 1:
        raise ValueError("block-count en az 1 olmali.")

    # Import TensorFlow-backed task code only after CLI validation. This keeps
    # ``feature_ranking.py --help`` and argument errors lightweight.
    from src.workflow import run_experiment

    dataset_base = dataset_base_name(config.dataset_name)
    split_root = PROJECT_ROOT / "split_datasets"
    split_directory = split_root / dataset_base
    split_result = split_dataset_by_features(
        SplitOptions(
            input_file=config.dataset_name,
            number_of_blocks=block_count,
            target_column=config.target_column,
            output_directory=split_directory,
            id_column=config.id_column,
            write_feature_ranking_files=True,
            feature_ranking_raw_dir=PROJECT_ROOT / "data" / "raw",
        )
    )

    feature_filename = f"top_{_percent_tag(config.feature_percent)}_max_abs_features.csv"
    selection_root = _selection_output_root(config.task.lower().strip())
    selected_paths: list[Path] = []

    for block_data_path in split_result["run_autoencoder_data_files"]:
        block_config = replace(
            config,
            dataset_name=block_data_path.name,
            # Split pairs contain features and labels only; the original ID
            # column has already been removed by split_dataset_by_features().
            id_column=None,
        )
        print(f"\n[DC] Blok FeatureRank: {block_data_path.name}")
        run_experiment(block_config)

        block_output_dir = selection_root / block_data_path.stem
        candidates = sorted(block_output_dir.rglob(feature_filename))
        if not candidates:
            raise FileNotFoundError(
                f"Blok secim dosyasi bulunamadi: {block_output_dir / feature_filename}"
            )
        selected_paths.extend(candidates)

    final_output = split_root / f"{dataset_base}_selected_features_combined.csv"
    combined_result = combine_selected_features(
        CombineOptions(
            input_file=config.dataset_name,
            selected_features_dir=selection_root,
            selected_features_glob=f"**/{feature_filename}",
            target_column=config.target_column,
            output_file=final_output,
            id_column=config.id_column,
            mapping_file=split_result["mapping_path"],
            write_feature_ranking_files=True,
            feature_ranking_raw_dir=PROJECT_ROOT / "data" / "raw",
            selected_feature_paths=selected_paths,
        )
    )

    final_data_path = combined_result["run_autoencoder_data_path"]
    if final_data_path is None:
        raise RuntimeError("Birlesik FeatureRank data dosyasi olusturulamadi.")

    print(f"\n[DC] Birlesik dataset ile final FeatureRank: {final_data_path.name}")
    return run_experiment(replace(config, dataset_name=Path(final_data_path).name, id_column=None))


def run_repeated_divide_combine(
    config: ExperimentConfig,
    repeat_runs: int,
    block_count: int,
    metric_path: Path,
    metric_name: str,
) -> tuple[list[float], float]:
    """Repeat DC with the same seed progression as the global workflow."""
    if repeat_runs < 1:
        raise ValueError("repeat-runs en az 1 olmali.")

    metric_values: list[float] = []
    durations: list[float] = []
    run_rows: list[dict] = []
    for run_index in range(repeat_runs):
        seed = config.random_state
        if seed is not None and repeat_runs > 1:
            seed += run_index
        print(f"\n[DC] Calisma {run_index + 1}/{repeat_runs} basladi.")
        started_at = time.perf_counter()
        _, filtered_metric = run_divide_combine(
            replace(config, random_state=seed), block_count=block_count
        )
        durations.append(time.perf_counter() - started_at)
        metric_values.append(float(filtered_metric))
        # DC's final task metrics belong to the combined dataset, not the
        # original dataset folder. Reading the original folder caused a
        # FileNotFoundError after an otherwise successful DC run.
        combined_name = (
            f"{dataset_base_name(config.dataset_name)}_" "selected_features_combined_data.csv"
        )
        final_config = replace(config, dataset_name=combined_name)
        run_rows.append(collect_run_row(final_config, run_index + 1, durations[-1]))

    lower_is_better = metric_name == "Cluster_RMSE"
    sorted_values = sorted(metric_values, reverse=not lower_is_better)
    metric_path.parent.mkdir(parents=True, exist_ok=True)
    metric_path.write_text(
        f"{metric_values}\n"
        f"Sirali {metric_name}: {sorted_values}\n"
        f"Run sureleri saniye: {[round(value, 3) for value in durations]}",
        encoding="utf-8",
    )
    save_repeated_run_tables(config, run_rows)
    return metric_values, sum(metric_values) / len(metric_values)
